---
title: "Exp10 - Corrected synapses and stdp effects?"
author: "Erik J Peterson"
date: ""
output: html_document
---


```{r helper_fns, echo=FALSE, fig.width=6, fig.height=4, echo=FALSE, warning=FALSE, message=FALSE}
library(ggplot2)
library(grid)
library(gridExtra)
library(plyr)
library(dplyr)
library(reshape)
library(png)
library(psd)
library(tidyr)
library(doParallel)
library(bspec)
registerDoParallel(cores=10)

source("loaders.R")
path <- "/home/ejp/src/syncological/data/"
```


# Power and synchrony and fidelity

## Async + ING

Load ING and async.

```{r load_and_process, echo=FALSE, warning=FALSE, message=FALSE}
# --
# ING
js <- 1:20
tmppath <- paste(path, "/ing_exp10/", sep="")
I_es = c("0.0", "0.02", "0.04", "0.06", "0.08", "0.1")
ing10.I_e <- rbind(load.10.analysis(tmppath, name="I_e", vals=I_es, js, stdp=FALSE),
                   load.10.analysis(tmppath, name="I_e", vals=I_es, js, stdp=TRUE)
                   )

tmppath <- paste(path, "/ing_exp11/", sep="")
w_ies <- c("1.0", "1.2", "1.4", "1.6", "1.8", "2.0")
ing10.w_ie <- rbind(load.10.analysis(tmppath, name="w_ie", vals=w_ies, js, stdp=FALSE),
                   load.10.analysis(tmppath, name="w_ie", vals=w_ies, js, stdp=TRUE)
                   )

tmppath <- paste(path, "/ing_exp12/", sep="")
w_ees <- c("0.1", "0.2", "0.3", "0.4", "0.5")
ing10.w_ee <- rbind(load.10.analysis(tmppath, name="w_ee", vals=w_ees, js, stdp=FALSE),
                   load.10.analysis(tmppath, name="w_ee", vals=w_ees, js, stdp=TRUE)
                   )

tmppath <- paste(path, "/ing_exp13/", sep="")
rates <- c("5", "10", "15", "20", "25", "30")
ing10.rate <- rbind(load.10.analysis(tmppath, name="rate", vals=rates, js, stdp=FALSE),
                   load.10.analysis(tmppath, name="rate", vals=rates, js, stdp=TRUE)
                   )
ing10.rate$rate <- factor(ing10.rate$rate, levels=rates)

# --
# PING
js <- 1:20
tmppath <- paste(path, "/ping_exp10/", sep="")
I_es = c("0.0", "0.02", "0.04", "0.06", "0.08", "0.1")
ping10.I_e <- rbind(load.10.analysis(tmppath, name="I_e", vals=I_es, js, stdp=FALSE),
                   load.10.analysis(tmppath, name="I_e", vals=I_es, js, stdp=TRUE)
                   )

tmppath <- paste(path, "/ping_exp11/", sep="")
w_ies <- c("1.0", "1.2", "1.4", "1.6", "1.8", "2.0")
ping10.w_ie <- rbind(load.10.analysis(tmppath, name="w_ie", vals=w_ies, js, stdp=FALSE),
                   load.10.analysis(tmppath, name="w_ie", vals=w_ies, js, stdp=TRUE)
                   )

tmppath <- paste(path, "/ping_exp12/", sep="")
w_ees <- c("0.1", "0.2", "0.3", "0.4", "0.5")
ping10.w_ee <- rbind(load.10.analysis(tmppath, name="w_ee", vals=w_ees, js, stdp=FALSE),
                   load.10.analysis(tmppath, name="w_ee", vals=w_ees, js, stdp=TRUE)
                   )

tmppath <- paste(path, "/ping_exp13/", sep="")
rates <- c("5", "10", "15", "20", "25", "30")
ping10.rate <- rbind(load.10.analysis(tmppath, name="rate", vals=rates, js, stdp=FALSE),
                   load.10.analysis(tmppath, name="rate", vals=rates, js, stdp=TRUE)
                   )
ping10.rate$rate <- factor(ping10.rate$rate, levels=rates)

# # 
# # -----------------------------------------------------------------------
# # poprates
# # Even sampling
# # ING
# w_ies <- c("0.1", "0.2", "0.3", "0.4", "0.5", "0.60", "0.70", "0.8", "0.9", "1.0")
# js <- 1:20
# 
# tmppath <- paste(path, "/ing_exp5/", sep="")
# ing1.poprate.e <- load.ing1.poprates(tmppath, "e", rates, w_ies, js)
# ing1.poprate.i <- load.ing1.poprates(tmppath, "i", rates, w_ies, js)
# 
# ing1.spec <- NULL
# for(w_ie in w_ies){
#   mask <- ing1.poprate.e$w_ie == w_ie
#   prate <- ing1.poprate.e[mask,'poprate']
#   
#   spec <- pspectrum(prate, x.frqsamp=10000)
#   ing1.spec <- rbind(
#     ing1.spec,
#     data.frame(
#       spec=spec$spec, 
#       freq=spec$freq, 
#       w_ie=rep(w_ie, length(spec$spec))
#       )
#     )
#   }
# 
# ing1.power <- NULL
# for(w_ie_i in w_ies){
#   sel <- filter(ing1.spec, w_ie == w_ie_i, freq > 10, freq < 30)
#   ing1.power <- rbind(
#     ing1.power,
#     data.frame(
#       M = mean(log10(sel$spec)),
#       SD = sd(log10(sel$spec)),
#       w_ie = w_ie_i 
#     )  
#   )
# }
# 
# ing1.spec.pre <- NULL
# for(w_ie_i in w_ies){
#   prate <- filter(ing1.poprate.e, w_ie == w_ie_i, sample_time > .2, sample_time < 0.5)[['poprate']]
#   spec <- pspectrum(prate, x.frqsamp=10000)
#   ing1.spec.pre <- rbind(
#     ing1.spec.pre,
#     data.frame(
#       spec=spec$spec, 
#       freq=spec$freq, 
#       w_ie=rep(w_ie, length(spec$spec))
#       )
#     )
#   }
# 
# ing1.power.pre <- NULL
# for(w_ie_i in w_ies){
#   sel <- filter(ing1.spec.pre, w_ie == w_ie_i, freq > 10, freq < 30)
#   ing1.power.pre <- rbind(
#     ing1.power,
#     data.frame(
#       M = mean(log10(sel$spec)),
#       SD = sd(log10(sel$spec)),
#       w_ie = w_ie_i 
#     )  
#   )
# }
# 
# ing1.power$stat <- rep("Post", nrow(ing1.power))
# ing1.power.pre$stat <- rep("Pre", nrow(ing1.power.pre))
# ing1.power <- rbind(ing1.power, ing1.power.pre)
# 
# # PING
# w_eis <- c("1.0", "1.1", "1.2", "1.3", "1.4", "1.5")
# w_ies <- c("0.1", "0.2", "0.3", "0.4", "0.5", "0.60", "0.70", "0.8", "0.9", "1.0")
# js <- 1:20
# 
# tmppath <- paste(path, "/ping_exp5/", sep="")
# ping1.poprate.e <- load.ping1.poprates(tmppath, "e", rates, w_eis, w_ies, js)
# ping1.poprate.i <- load.ping1.poprates(tmppath, "i", rates, w_eis, w_ies, js)
# 
# ping1.spec <- NULL
# for(w_ie_i in w_ies){
#   for(w_ei_i in w_eis){
#     prate <- filter(ping1.poprate.e, w_ei == w_ei_i, w_ie == w_ie_i)[['poprate']]
#   
#     spec <- pspectrum(prate, x.frqsamp=10000)
#     ping1.spec <- rbind(
#       ping1.spec,
#       data.frame(
#         spec=spec$spec, 
#         freq=spec$freq, 
#         w_ie=rep(w_ie_i, length(spec$spec)),
#         w_ei=rep(w_ei_i, length(spec$spec))
#       )
#     )
#   }
# }
# 
# ping1.power <- NULL
# for(w_ie_i in w_ies){
#   for(w_ei_i in w_eis){
#     sel <- filter(ping1.spec, w_ei == w_ei_i, w_ie == w_ie_i, freq > 10, freq < 30)
#     ping1.power <- rbind(
#       ping1.power,
#       data.frame(
#         M = mean(log10(sel$spec)),
#         SD = sd(log10(sel$spec)),
#         w_ie = w_ie_i,
#         w_ei = w_ei_i 
#       )  
#     )
#   }
# }
# 
# ping1.spec.pre <- NULL
# for(w_ie_i in w_ies){
#   for(w_ei_i in w_eis){
#     prate <- filter(ping1.poprate.e, w_ei == w_ei_i, 
#                     w_ie == w_ie_i, sample_time > .2, sample_time < 0.5)[['poprate']]
#     spec <- pspectrum(prate, x.frqsamp=10000)
#     ping1.spec.pre <- rbind(
#       ping1.spec.pre,
#       data.frame(
#         spec=spec$spec, 
#         freq=spec$freq, 
#         w_ie=rep(w_ie_i, length(spec$spec)),
#         w_ei=rep(w_ei_i, length(spec$spec))
#       )
#     )
#   }
# }
# 
# ping1.power.pre <- NULL
# for(w_ie_i in w_ies){
#   for(w_ei_i in w_eis){
#     sel <- filter(ping1.spec.pre, w_ei == w_ei_i, w_ie == w_ie_i, freq > 10, freq < 30)
#     ping1.power.pre <- rbind(
#       ping1.power,
#       data.frame(
#         M = mean(log10(sel$spec)),
#         SD = sd(log10(sel$spec)),
#         w_ie = w_ie_i,
#         w_ei = w_ei_i 
#       )  
#     )
#   }
# }
# 
# ping1.power$stat <- rep("Post", nrow(ping1.power))
# ping1.power.pre$stat <- rep("Pre", nrow(ping1.power.pre))
# ping1.power <- rbind(ping1.power, ping1.power.pre)
```



```{r ing10=13}
ing10.I_e %>%
  group_by(stdp, stat, I_e) %>%
  summarise(M=mean(x), SD=sd(x)) ->
  ing10.I_e.m

ing10.w_ie %>%
  group_by(stdp, stat, w_ie) %>%
  summarise(M=mean(x), SD=sd(x)) ->
  ing10.w_ie.m

ing10.w_ee %>%
  group_by(stdp, stat, w_ee) %>%
  summarise(M=mean(x), SD=sd(x)) ->
  ing10.w_ee.m

ing10.rate %>%
  group_by(stdp, stat, rate) %>%
  summarise(M=mean(x), SD=sd(x)) ->
  ing10.rate.m

limits <- aes(ymax = M + SD, ymin=M - SD)

# ing1.power %>% 
#   filter(stat %in% c("Post")) %>%
#   ggplot(aes(x=w_ie, y=M, group=w_ie)) + 
#   scale_color_manual(values=c("black", "grey")) +
#   geom_point(size=4, position = "jitter") +
#   theme_classic() + 
#   theme(legend.position="top") +
#   xlab(expression(w[IE])) +
#   ylab("log(Power)") -> p.ing1.power.e
# # print(p.ing1.isi.e)

ing10.I_e.m %>% 
  filter(stat %in% c("isi_e")) %>%
  ggplot(aes(x=I_e, y=M, group=I_e, color=stdp)) + 
  geom_errorbar(limits, width=0.2, color="grey") + 
  geom_point(size=4) +
  ylim(0.8, 1) +
  theme_classic() + 
  xlab(expression(I[E])) +
  ylab("ISI synchrony") -> plot.ing10.I_e.m
# print(plot.ing10.I_e.m)

ing10.w_ie.m %>% 
  filter(stat %in% c("isi_e")) %>%
  ggplot(aes(x=w_ie, y=M, group=w_ie, color=stdp)) + 
  geom_errorbar(limits, width=0.2, color="grey") + 
  geom_point(size=4) +
  ylim(0.8, 1) +
  theme_classic() + 
  xlab(expression(w[IE])) +
  ylab("ISI synchrony") -> plot.ing10.w_ie.m

ing10.w_ee.m %>% 
  filter(stat %in% c("isi_e")) %>%
  ggplot(aes(x=w_ee, y=M, group=w_ee, color=stdp)) + 
  geom_errorbar(limits, width=0.2, color="grey") + 
  geom_point(size=4) +
  ylim(0.8, 1) +
  theme_classic() + 
  xlab(expression(w[EE])) +
  ylab("ISI synchrony") -> plot.ing10.w_ee.m

ing10.rate.m %>% 
  filter(stat %in% c("isi_e")) %>%
  ggplot(aes(x=rate, y=M, group=rate, color=stdp)) + 
  geom_errorbar(limits, width=0.2, color="grey") + 
  geom_point(size=4) +
  ylim(0.8, 1) +
  theme_classic() + 
  xlab("rate") +
  ylab("ISI synchrony") -> plot.ing10.rate.m

laym = t(rbind(
  c(1, 2, 3, 4)
))
grid.arrange(plot.ing10.I_e.m, plot.ing10.w_ie.m, plot.ing10.w_ee.m, plot.ing10.rate.m, layout_matrix=laym)

# lev
ing10.I_e.m %>% 
  filter(stat %in% c("lev_e")) %>%
  filter(stdp == TRUE) %>%
  ggplot(aes(x=I_e, y=M, group=I_e, color=stdp)) + 
  geom_errorbar(limits, width=0.2, color="grey") + 
  geom_point(size=4) +
#   ylim(0.8, 1) +
  theme_classic() + 
  xlab(expression(I[E])) +
  ylab("ISI synchrony") -> plot.lev.ing10.I_e.m
# print(plot.ing10.I_e.m)

ing10.w_ie.m %>% 
  filter(stat %in% c("lev_e")) %>%
  filter(stdp == TRUE) %>%
  ggplot(aes(x=w_ie, y=M, group=w_ie, color=stdp)) + 
  geom_errorbar(limits, width=0.2, color="grey") + 
  geom_point(size=4) +
#   ylim(0.8, 1) +
  theme_classic() + 
  xlab(expression(w[IE])) +
  ylab("ISI synchrony") -> plot.lev.ing10.w_ie.m

ing10.w_ee.m %>% 
  filter(stat %in% c("lev_e")) %>%
  filter(stdp == TRUE) %>%
  ggplot(aes(x=w_ee, y=M, group=w_ee, color=stdp)) + 
  geom_errorbar(limits, width=0.2, color="grey") + 
  geom_point(size=4) +
#   ylim(0.8, 1) +
  theme_classic() + 
  xlab(expression(w[EE])) +
  ylab("ISI synchrony") -> plot.lev.ing10.w_ee.m

ing10.rate.m %>% 
  filter(stat %in% c("lev_e")) %>%
  filter(stdp == TRUE) %>%
  ggplot(aes(x=rate, y=M, group=rate, color=stdp)) + 
  geom_errorbar(limits, width=0.2, color="grey") + 
  geom_point(size=4) +
#   ylim(0.8, 1) +
  theme_classic() + 
  xlab("rate") +
  ylab("ISI synchrony") -> plot.lev.ing10.rate.m

# print(plot.ing10.w_ie.m)

laym = t(rbind(
  c(1, 2, 3, 4)
))
grid.arrange(plot.lev.ing10.I_e.m, plot.lev.ing10.w_ie.m, plot.lev.ing10.w_ee.m, plot.lev.ing10.rate.m, layout_matrix=laym)

# ing1.m$stat <- revalue(ing1.m$stat, c("fano_e"="Post", "fano_pre_e"="Pre"))
# ing1.m %>% 
#   filter(stat %in% c("Pre", "Post")) %>%
#   ggplot(aes(x=w_ie, y=M, group=w_ie, color=stat)) + 
#   geom_errorbar(limits, width=0.2, color="grey") + 
#   geom_point(size=4) +
#   scale_color_manual(values=c("black", "grey")) +
#   geom_hline(yintercept=0.3, color="red") +
#   # stat_summary(fun.data = "mean_cl_boot", size=1) +
#   # geom_boxplot(width=0.1) + 
#   # ylim(0.5, 1) +
#   #     facet_grid(.~rate, scales = "free") +
#   theme_classic() + 
#   theme(legend.position="top") +
#   ylab("Fano factor") +
#   xlab(expression(w[IE])) -> p.ing1.fano.e
# # print(p.ing1.fano.e)

# ing1.m %>% 
#   filter(stat %in% c("lev_e")) %>%
#   ggplot(aes(x=w_ie, y=M, group=w_ie)) + 
#   geom_errorbar(limits, width=0.2, color="grey") + 
#   geom_point(size=4) +
#   # stat_summary(fun.data = "mean_cl_boot", size=1) +
#   # geom_boxplot(width=0.1) + 
#   # ylim(0.5, 1) +
#   #     facet_grid(.~rate, scales = "free") +
#   theme_classic() + 
#   xlab(expression(w[IE])) +
#   geom_hline(yintercept=464, color="red") +
#   ylab("Code fidelity") -> p.ing1.lev.e
# # print(p.ing1.lev.e)
# 
# # laym = rbind(
# #   c(4, 4, 4, 1, 1, 1),
# #   c(2, 2, 2, 3, 3, 3)
# # )
# laym = rbind(
#   c(1, 2 ,3)
# )
# grid.arrange(p.ing1.power.e, p.ing1.isi.e, p.ing1.lev.e, layout_matrix=laym)
# # Need power now
```

```{r ing2}
ing2 %>%
  group_by(stat, rate, I_e) %>%
  summarise(M=mean(x), SD=sd(x)) ->
  ing2.m

limits <- aes(ymax = M + SD, ymin=M - SD)

ing2.power %>% 
  # filter(stat %in% c("Post")) %>%
  ggplot(aes(x=I_e, y=M, group=I_e)) + 
  scale_color_manual(values=c("black", "grey")) +
  geom_point(size=4, position = "jitter") +
  theme_classic() + 
  theme(legend.position="top") +
  xlab(expression(I[E])) +
  ylab("log(Power)") -> p.ing2.power.e
# print(p.ing2.isi.e)

ing2.m %>% 
  filter(stat %in% c("isi_e")) %>%
  ggplot(aes(x=I_e, y=M, group=I_e)) + 
  geom_errorbar(limits, width=0.2, color="grey") + 
  geom_point(size=4) +
  geom_hline(yintercept=0.82, color="red") +
  geom_hline(yintercept=0.50, color="grey") +
  ylim(0.7, .9) +
  theme_classic() + 
  xlab(expression(I[E])) +
  ylab("ISI synchrony") -> p.ing2.isi.e
# print(p.ing2.isi.e)

ing2.m %>% 
  filter(stat %in% c("lev_e")) %>%
  ggplot(aes(x=I_e, y=M, group=I_e)) + 
  geom_errorbar(limits, width=0.2, color="grey") + 
  geom_point(size=4) +
  theme_classic() + 
  xlab(expression(I[E])) +
  geom_hline(yintercept=464, color="red") +
  ylab("Code fidelity") -> p.ing2.lev.e
# print(p.ing2.lev.e)

# laym = rbind(
#   c(4, 4, 4, 1, 1, 1),
#   c(2, 2, 2, 3, 3, 3)
# )
laym = rbind(
  c(1, 2, 3)
)
# grid.arrange(p.ing2.isi.e, p.ing2.lev.e, layout_matrix=laym)
grid.arrange(p.ing2.power.e, p.ing2.isi.e, p.ing2.lev.e, layout_matrix=laym)
```

```{r ing3}
ing3 %>%
  group_by(stat, rate, I_i_sigma) %>%
  summarise(M=mean(x), SD=sd(x)) ->
  ing3.m

limits <- aes(ymax = M + SD, ymin=M - SD)

# ing3.power %>% 
#   filter(stat %in% c("Post")) %>%
#   ggplot(aes(x=I_i_sigma, y=M, group=I_i_sigma)) + 
#   scale_color_manual(values=c("black", "grey")) +
#   geom_point(size=4, position = "jitter") +
#   theme_classic() + 
#   theme(legend.position="top") +
  # xlab(expression(I[sigma])) +
#   ylab("log(Power") -> p.ing3.power.e
# print(p.ing3.isi.e)

ing3.m %>% 
  filter(stat %in% c("isi_e")) %>%
  ggplot(aes(x=I_i_sigma, y=M, group=I_i_sigma)) + 
  geom_errorbar(limits, width=0.2, color="grey") + 
  geom_point(size=4) +
  geom_hline(yintercept=0.82, color="red") +
  geom_hline(yintercept=0.50, color="grey") +
  ylim(0.7, .9) +
  theme_classic() + 
  xlab(expression(I[sigma])) +
  ylab("ISI synchrony") -> p.ing3.isi.e
# print(p.ing3.isi.e)

ing3.m %>% 
  filter(stat %in% c("lev_e")) %>%
  ggplot(aes(x=I_i_sigma, y=M, group=I_i_sigma)) + 
  geom_errorbar(limits, width=0.2, color="grey") + 
  geom_point(size=4) +
  theme_classic() + 
  xlab(expression(I[sigma])) +
  geom_hline(yintercept=464, color="red") +
  ylab("Code fidelity") -> p.ing3.lev.e
# print(p.ing3.lev.e)

laym = rbind(
  c(1, 2)
)
grid.arrange(p.ing3.isi.e, p.ing3.lev.e, layout_matrix=laym)
# grid.arrange(p.ing3.power.e, p.ing3.isi.e, p.ing3.lev.e, layout_matrix=laym)
# Need power now
```

```{r ping1}
ping1 %>%
  group_by(stat, rate, w_ie) %>%
  summarise(M=mean(x), SD=sd(x)) ->
  ping1.m

limits <- aes(ymax = M + SD, ymin=M - SD)

ping1.power %>% 
  group_by(stat, w_ie) %>% 
  summarise(M = mean(M), SD = mean(SD)) %>% 
  filter(stat %in% c("Post")) %>%
  ggplot(aes(x=w_ie, y=M, group=w_ie)) + 
  # geom_errorbar(limits, width=0.2, color="grey") +
  scale_color_manual(values=c("black", "grey")) +
  geom_point(size=4, position = "jitter") +
  theme_classic() + 
  theme(legend.position="top") +
  xlab(expression(w[IE])) +
  ylab("log(Power)") -> p.ping1.power.e
# print(p.ping1.isi.e)

ping1.m %>% 
  filter(stat %in% c("isi_e")) %>%
  ggplot(aes(x=w_ie, y=M, group=w_ie)) + 
  geom_errorbar(limits, width=0.2, color="grey") + 
  geom_point(size=4) +
  geom_hline(yintercept=0.50, color="grey") +
  ylim(0.7, .9) +
  geom_hline(yintercept=0.82, color="red") +
  theme_classic() + 
  xlab(expression(w[IE])) +
  ylab("ISI synchrony") -> p.ping1.isi.e
# print(p.ping1.isi.e)

ping1.m %>% 
  filter(stat %in% c("lev_e")) %>%
  ggplot(aes(x=w_ie, y=M, group=w_ie)) + 
  geom_errorbar(limits, width=0.2, color="grey") + 
  geom_point(size=4) +
  # stat_summary(fun.data = "mean_cl_boot", size=1) +
  # geom_boxplot(width=0.1) + 
  # ylim(0.5, 1) +
  #     facet_grid(.~rate, scales = "free") +
  theme_classic() + 
  xlab(expression(w[IE])) +
  geom_hline(yintercept=464, color="red") +
  ylab("Code fidelity") -> p.ping1.lev.e
# print(p.ping1.lev.e)

# laym = rbind(
#   c(4, 4, 4, 1, 1, 1),
#   c(2, 2, 2, 3, 3, 3)
# )
laym = rbind(
  c(1, 2, 3)
)
grid.arrange(p.ping1.power.e, p.ping1.isi.e, p.ping1.lev.e, layout_matrix=laym)
# Need power now
```

```{r ping1_examples}
ping1.poprate.e %>% 
  filter(w_ie %in% c("0.1", "0.3", "0.60", "0.9")) %>% 
  filter(w_ei == "1.0") %>% 
  ggplot(aes(x=sample_time, y=poprate)) +
  geom_line() +
  ylab("Avg. pop. rate (Hz)") +
  xlab("Time (s)") +
  theme_classic() +
  facet_grid(w_ie~.)
```

```{r ping1_ei}
ping1 %>%
  group_by(stat, rate, w_ei) %>%
  summarise(M=mean(x), SD=sd(x)) ->
  ping1.m.ei

limits <- aes(ymax = M + SD, ymin=M - SD)

ping1.m.ei %>% 
  filter(stat %in% c("isi_e")) %>%
  ggplot(aes(x=w_ei, y=M, group=w_ei)) + 
  geom_errorbar(limits, width=0.2, color="grey") + 
  geom_point(size=4) +
  geom_hline(yintercept=0.82, color="red") +
  geom_hline(yintercept=0.50, color="grey") +
  ylim(0.7, .9) +
  theme_classic() + 
  xlab(expression(w[EI])) +
  ylab("ISI synchrony") -> p.ping1.isi.ei.e
print(p.ping1.isi.ei.e)

# ping1.m.ei$stat <- revalue(ping1.m.ei$stat, c("fano_e"="Post", "fano_pre_e"="Pre"))
# ping1.m.ei %>% 
#   filter(stat %in% c("Pre", "Post")) %>%
#   ggplot(aes(x=w_ei, y=M, group=w_ei, color=stat)) + 
#   geom_errorbar(limits, width=0.2, color="grey") + 
#   geom_point(size=4) +
#   scale_color_manual(values=c("black", "grey")) +
#   geom_hline(yintercept=0.3, color="red") +
#   # stat_summary(fun.data = "mean_cl_boot", size=1) +
#   # geom_boxplot(width=0.1) + 
#   # ylim(0.5, 1) +
#   #     facet_grid(.~rate, scales = "free") +
#   theme_classic() + 
#   ylab("Fano factor") +
#   xlab(expression(w[EI])) -> p.ping1.fano.ei.e
# print(p.ping1.fano.ei.e)

# ping1.m.ei %>% 
#   filter(stat %in% c("lev_e")) %>%
#   ggplot(aes(x=w_ei, y=M, group=w_ei)) + 
#   geom_errorbar(limits, width=0.2, color="grey") + 
#   geom_point(size=4) +
#   geom_hline(yintercept=464, color="red") +
#   # stat_summary(fun.data = "mean_cl_boot", size=1) +
#   # geom_boxplot(width=0.1) + 
#   # ylim(0.5, 1) +
#   #     facet_grid(.~rate, scales = "free") +
#   theme_classic() + 
#   xlab(expression(w[EI])) +
#   ylab("Code fidelity") -> p.ping1.lev.ei.e
# # print(p.ping1.lev.ei.e)
# 
# laym = rbind(
#   c(1, 1, 1, 2, 2, 4, 4)
# )
# grid.arrange(p.ping1.fano.ei.e, p.ping1.isi.ei.e, p.ping1.lev.ei.e, layout_matrix=laym)
# # Need power now
```


```{r ping2}
ping2 %>%
  group_by(stat, rate, I_e) %>%
  summarise(M=mean(x), SD=sd(x)) ->
  ping2.m

limits <- aes(ymax = M + SD, ymin=M - SD)

ping2.power %>% 
  # filter(stat %in% c("Post")) %>%
  ggplot(aes(x=I_e, y=M, group=I_e)) + 
  scale_color_manual(values=c("black", "grey")) +
  geom_point(size=4, position = "jitter") +
  theme_classic() + 
  theme(legend.position="top") +
  xlab(expression(I[E])) +
  ylab("log(Power)") -> p.ping2.power.e
print(p.ping2.isi.e)

ping2.m %>% 
  filter(stat %in% c("isi_e")) %>%
  ggplot(aes(x=I_e, y=M, group=I_e)) + 
  geom_errorbar(limits, width=0.2, color="grey") + 
  geom_point(size=4) +
  geom_hline(yintercept=0.82, color="red") +
  geom_hline(yintercept=0.50, color="grey") +
  ylim(0.7, .9) +
  theme_classic() + 
  xlab(expression(I[E])) +
  ylab("ISI synchrony") -> p.ping2.isi.e
# print(p.ping2.isi.e)

ping2.m %>% 
  filter(stat %in% c("lev_e")) %>%
  ggplot(aes(x=I_e, y=M, group=I_e)) + 
  geom_errorbar(limits, width=0.2, color="grey") + 
  geom_point(size=4) +
  theme_classic() + 
  xlab(expression(I[E])) +
  geom_hline(yintercept=464, color="red") +
  ylab("Code fidelity") -> p.ping2.lev.e
# print(p.ping2.lev.e)

# laym = rbind(
#   c(4, 4, 4, 1, 1, 1),
#   c(2, 2, 2, 3, 3, 3)
# )
laym = rbind(
  c(1, 2, 3)
)
# grid.arrange(p.ping2.isi.e, p.ping2.lev.e, layout_matrix=laym)
grid.arrange(p.ping2.power.e, p.ping2.isi.e, p.ping2.lev.e, layout_matrix=laym)
```

```{r async1}
async1 %>%
  group_by(stat, rate, w_ie) %>%
  summarise(M=mean(x), SD=sd(x)) ->
  async1.m

limits <- aes(ymax = M + SD, ymin=M - SD)

async1.m %>% 
  filter(stat %in% c("isi_e")) %>%
  ggplot(aes(x=w_ie, y=M, group=w_ie)) + 
  geom_errorbar(limits, width=0.2, color="grey") + 
  geom_point(size=4) +
  # stat_summary(fun.data = "mean_cl_boot", size=1) +
  # geom_boxplot(width=0.1) + 
  # ylim(0.5, 1) +
  #     facet_grid(.~rate, scales = "free") +
  theme_classic() + 
  xlab(expression(w[IE])) +
  ylab("ISI synchrony") -> p.async1.isi.e
# print(p.async1.isi.e)

async1.m$stat <- revalue(async1.m$stat, c("fano_e"="Post", "fano_pre_e"="Pre"))
async1.m %>% 
  filter(stat %in% c("Pre", "Post")) %>%
  ggplot(aes(x=w_ie, y=M, group=w_ie, color=stat)) + 
  geom_errorbar(limits, width=0.2, color="grey") + 
  geom_point(size=4) +
  scale_color_manual(values=c("black", "grey")) +
  # stat_summary(fun.data = "mean_cl_boot", size=1) +
  # geom_boxplot(width=0.1) + 
  # ylim(0.5, 1) +
  #     facet_grid(.~rate, scales = "free") +
  theme_classic() + 
  ylab("Fano factor") +
  xlab(expression(w[IE])) -> p.async1.fano.e
# print(p.async1.fano.e)

async1.m %>% 
  filter(stat %in% c("lev_e")) %>%
  ggplot(aes(x=w_ie, y=M, group=w_ie)) + 
  geom_errorbar(limits, width=0.2, color="grey") + 
  geom_point(size=4) +
  # stat_summary(fun.data = "mean_cl_boot", size=1) +
  # geom_boxplot(width=0.1) + 
  # ylim(0.5, 1) +
  #     facet_grid(.~rate, scales = "free") +
  theme_classic() + 
  xlab(expression(w[IE])) +
  ylab("Code fidelity") -> p.async1.lev.e
# print(p.async1.lev.e)

laym = rbind(
  c(1, 1, 1, 2, 2, 4, 4)
)
grid.arrange(p.async1.fano.e, p.async1.isi.e, p.async1.lev.e, layout_matrix=laym)
# Need power now
```

Gather stats, PSDs, power, poprates, and raster

Show raster and rate. PSD.

Then show power and sync and fano. Next to it show L-distance.

## Async and PING.

Repeat as above.

