---
title: "Results"
author: "Erik J Peterson"
date: "8-28-2015"
output:
  html_document:
    number_sections: yes
    theme: spacelab
    toc: yes
---

```{r helper_fns, echo=FALSE, fig.width=6, fig.height=4, echo=FALSE, warning=FALSE, message=FALSE}
library(ggplot2)
library(grid)
library(gridExtra)
library(plyr)
library(dplyr)
library(reshape)
library(png)
library(psd)
library(tidyr)
library(doParallel)
library(bspec)
registerDoParallel(cores=10)

path <- "/home/ejp/src/syncological/data"

load.ing.analysis <- function(path, rates, w_ies, js){
  df <- NULL
  for(r_s in rates){
    for(w_ie in w_ies){
      for(j in js){
          try({
            # rate-{1}_ie-{2}_j-{3}
            name <- paste("rate-", as.character(r_s), 
                          "_ie-", as.character(w_ie),
                          "_j-", as.character(j), 
                          "_analysis.csv", sep="")
            dat <- read.csv(paste(path, name, sep=""), header=FALSE)
            colnames(dat) <- c("stat", "x")
            dat["rate"] <- rep(r_s, nrow(dat))
            dat["w_ie"] <- rep(w_ie, nrow(dat))
            dat["j"] <- rep(j, nrow(dat))
            df <- rbind(df, dat)  
          })  
      }
    }
  }
  df
}

load.ping.analysis <- function(path, rates, w_eis, w_ies, js){
  df <- NULL
  for(r_s in rates){
    for(w_ie in w_ies){
      for(w_ei in w_eis){
        for(j in js){
          try({
#             rate-5_ei-1.0_ie-0.2_j-13_analysis
            name <- paste("rate-", as.character(r_s),
                          "_ei-", as.character(w_ei),
                          "_ie-", as.character(w_ie),
                          "_j-", as.character(j), 
                          "_analysis.csv", sep="")
            dat <- read.csv(paste(path, name, sep=""), header=FALSE)
            colnames(dat) <- c("stat", "x")
            dat["rate"] <- rep(r_s, nrow(dat))
            dat["w_ei"] <- rep(w_ei, nrow(dat))
            dat["w_ie"] <- rep(w_ie, nrow(dat))
            dat["j"] <- rep(j, nrow(dat))
            df <- rbind(df, dat)  
          })  
        }
      }
    }
  }
  df
}

load.async.analysis <- function(path, rates, js){
  df <- NULL
  for(r_s in rates){
    for(j in js){
      try({
        # rate-{1}_ie-{2}_j-{3}
        name <- paste("rate-", as.character(r_s), 
                      "_j-", as.character(j), 
                      "_analysis.csv", sep="")
        dat <- read.csv(paste(path, name, sep=""), header=FALSE)
        colnames(dat) <- c("stat", "x")
        dat["rate"] <- rep(r_s, nrow(dat))
        dat["w_ei"] <- rep("0.1", nrow(dat))
        dat["w_ie"] <- rep("0.5", nrow(dat))
        dat["j"] <- rep(j, nrow(dat))
        df <- rbind(df, dat)  
        })  
      }
    }
  df
}
```

```{r load_ing, echo=FALSE, warning=FALSE, message=FALSE}
rates <- c(5, 10, 30)
# all
# w_ies <- c("0.1", "0.2", "0.3", "0.4", "0.5", "0.52", "0.54", 
#            "0.56", "0.58", "0.60", "0.70", "0.8", "0.9", "1.0")

# Even sampling
w_ies <- c("0.1", "0.2", "0.3", "0.4", "0.5", "0.60", "0.70", "0.8", "0.9", "1.0")
js <- 1:20

tmppath <- paste(path, "/ing_exp1/", sep="")
ing1 <- load.ing.analysis(tmppath, rates, w_ies, js)
```

```{r load_ping, echo=FALSE, warning=FALSE, message=FALSE}
# rates <- c(5, 10, 30)
rates <- c(5)

# Even sampling
w_eis <- c("1.0", "1.1", "1.2", "1.3", "1.4", "1.5")
w_ies <- c("0.1", "0.2", "0.3", "0.4", "0.5", "0.60", "0.70", "0.8", "0.9", "1.0")

# All
# w_eis <- c("1.0", "1.01", "1.02", "1.03", "1.04", "1.04", "1.06", "1.08", "1.09", 
#            "1.1", "1.2", "1.3", "1.4", "1.5")
# w_ies <- c("0.1", "0.2", "0.3", "0.4", "0.5", "0.52", "0.54", "0.56", 
#            "0.58", "0.60", "0.70", "0.8", "0.9", "1.0")
js <- 1:20

tmppath <- paste(path, "/ping_exp1/", sep="")
ping1 <- load.ping.analysis(tmppath, rates, w_eis, w_ies, js)
```

```{r load_async, echo=FALSE, warning=FALSE, message=FALSE}
rates <- c(5, 10, 30)
js <- 1:20

tmppath <- paste(path, "/async_exp1_type/", sep="")
async1 <- load.async.analysis(tmppath, rates, js)
```

# Analysis

## TODO

- Plot against spectral power.

## `w_ie` 

```{r plot_async_isi}
async1 %>%
  filter(stat %in% c("isi_e")) %>%
  ggplot(aes(x=rate, y=x, group=rate)) + 
    geom_boxplot() + 
#     facet_grid(.~rate, scales = "free") +
    theme_classic() + 
    theme(strip.background = element_blank(), strip.text.y = element_text(angle = 0)) +
    xlab("Rate (Hz)") +
    ylab("")
```

```{r plot_async_fano}
async1 %>%
  filter(stat %in% c("fano_pre_e", "fano_e")) %>%
  ggplot(aes(x=rate, y=x, group=interaction(rate,stat), color=stat)) + 
    geom_boxplot() + 
#     facet_grid(.~rate, scales = "free") +
    theme_classic() + 
    theme(strip.background = element_blank(), strip.text.y = element_text(angle = 0)) +
    xlab("Rate (Hz)") +
    ylab("Fano")
```

```{r plot_ing_isi}
ing1 %>%
  filter(stat %in% c("isi_e")) %>%
  ggplot(aes(x=as.numeric(w_ie), y=x, group=interaction(w_ie, rate), fill=as.factor(rate))) + 
    geom_boxplot() + 
#     facet_grid(.~rate, scales = "free") +
    theme_classic() + 
    theme(strip.background = element_blank(), strip.text.y = element_text(angle = 0)) +
    xlab("w_ie (msiemens)") +
    ylab("ISI Synchrony")
```

```{r plot_ing_fano}
ing1 %>%
  filter(stat %in% c("fano_e")) %>%
  ggplot(aes(x=as.numeric(w_ie), y=x, group=interaction(w_ie, rate), fill=as.factor(rate))) + 
    geom_boxplot() + 
#     facet_grid(.~rate, scales = "free") +
    theme_classic() + 
    theme(strip.background = element_blank(), strip.text.y = element_text(angle = 0)) +
    xlab("w_ie (msiemens)") +
    ylab("ISI Synchrony")
```

```{r plot_ping}
# ie
ping1 %>%
#   select(-w_ei) %>%
  filter(stat %in% c("fano_e", "fano_pre_e")) %>%
  ggplot(aes(x=w_ie, y=x, group=w_ie, color=stat)) + 
  geom_point() + 
#   facet_grid(rate~.) +
  theme_classic() 
```

* In both PING and ING, `w_ie` effects synchrony (ISI and sync),
* but not alway kappa or fano
* Stim onset greatly enhances this effect

## `w_ei` 

```{r, eval=FALSE}
ping1 %>%
  select(-w_ie) %>%
  filter(stat %in% c("fano_e", "fano_pre_e")) %>%
  ggplot(aes(x=w_ei, y=x, group=w_ei, color=stat)) + 
  geom_point() + 
#   facet_grid(rate~.) +
  theme_classic()
```

```{r}
ping1 %>%
  filter(stat %in% c("isi_e")) %>%
  ggplot(aes(x=w_ei, y=w_ie, fill=x)) + 
  geom_tile() + 
  scale_fill_continuous(low="white", high="red") +
#   facet_grid(rate~.) +
  theme_classic()
```

* `w_ei` doesn't effect synchrony.